apiVersion: v1
kind: Service
metadata:
  labels:
    controller: wmqcontroller
    creator: spade
    name: wmqcontroller
    project: eppe
    service: mq-service
    stack: eppe
    type: service
    zone: app
  name: mq-service.app
  namespace: app
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 22
      nodePort: 32222
      targetPort: 22
    - name: port-1414
      port: 1414
      nodePort: 31414
      targetPort: 1414
    - name: port-1415
      port: 1415
      nodePort: 31415
      targetPort: 1415
  selector:
    creator: spade
    name: wmqpod
