apiVersion: v1
kind: Service
metadata:
  labels:
    controller: datawascontroller
    creator: spade
    name: datawascontroller
    project: eppe
    service: datawas-service
    stack: eppe
    type: service
    zone: data
  name: datawas-service
  namespace: data
spec:
  type: NodePort
  ports:
    - name: admin
      port: 9060
      nodePort: 30061
      targetPort: 9060
    - name: http
      port: 9080
      nodePort: 30081
      targetPort: 9080
  selector:
    creator: spade
    name: datawaspod