apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    creator: spade
    name: datawascontroller
    type: replication
    zone: data
  name: datawascontroller
  namespace: data
spec:
  replicas: 1
  selector:
    creator: spade
    name: datawaspod
    type: pod
  template:
    metadata:
      labels:
        creator: spade
        name: datawaspod
        type: pod
    spec:
      containers:
      - image: nwtspaderegistry-on.azurecr.io/eppe/datazone:demo
        imagePullPolicy: Always
        name: datawaspod
        ports:
        - containerPort: 9060
          name: admin
          protocol: TCP
        - containerPort: 9080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
      nodeSelector:
        zone: data
      restartPolicy: Always