apiVersion: v1
kind: Service
metadata:
  labels:
    controller: appwascontroller
    creator: spade
    name: appwascontroller
    project: eppe
    service: appwas-service
    stack: eppe
    type: service
    zone: app
  name: appwas-service
  namespace: app
spec:
  type: NodePort
  ports:
    - name: admin
      port: 9060
      nodePort: 30060
      targetPort: 9060
    - name: http
      port: 9080
      nodePort: 30080
      targetPort: 9080
  selector:
    creator: spade
    name: appwaspod