name: MEAN Stack
description: |
  Deployment of a basic MEAN (MongoDB, Express, AngularJS, NodeJS) stack. Images pulled mainly from Dockerhub
version: 1.0
category: demo
maintainer: Brandon Adams
license: # The license
projectURL: newwave.io
