---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mediscan-activemq
  name: mediscan-activemq
  namespace: app
spec:
  ports:
  - name: mq
    nodePort: 31015
    port: 61616
    protocol: TCP
    targetPort: 61616
  selector:
    name: mediscan-activemq
  sessionAffinity: None
  type: NodePort
