---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mediscan-data
  name: mediscan-data
  namespace: data
spec:
  ports:
  - name: http
    nodePort: 30138
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    name: mediscan-data
  sessionAffinity: None
  type: NodePort
