---
apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    name: mediscan-activemq
  name: mediscan-activemq-rc
  namespace: app
spec:
  replicas: 1
  selector:
    name: mediscan-activemq
  template:
    metadata:
      labels:
        name: mediscan-activemq
    spec:
      containers:
      - image: rmohr/activemq
        imagePullPolicy: Always
        name: mediscan-activemq
        ports:
        - containerPort: 8161
          protocol: TCP
        - containerPort: 61616
          protocol: TCP
      nodeSelector:
        zone: app
      restartPolicy: Always
