---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mediscan-mongo-slave
  name: mediscan-mongo-slave
  namespace: data
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mediscan-mongo-slave
