---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mediscan-queue
  name: mediscan-queue
  namespace: app
spec:
  ports:
  - name: queue
    nodePort: 31320
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    name: mediscan-queue
  sessionAffinity: None
  type: NodePort
