---
apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    name: mediscan-nlp
  name: mediscan-nlp-rc
  namespace: app
spec:
  replicas: 1
  selector:
    name: mediscan-nlp
  template:
    metadata:
      labels:
        name: mediscan-nlp
    spec:
      containers:
      - image: nwtspaderegistry-on.azurecr.io/mediscan/nlp:0.0.1
        name: mediscan-nlp
        ports:
        - containerPort: 8080
          protocol: TCP
      nodeSelector:
        zone: app
      restartPolicy: Always
