.catalog:
  name: Mediscan # Name of the versioned template of the Catalog Entry
  version: v1.0 # Version of the versioned template of the Catalog Entry
  description: Mediscan catalog entry for demo purposes # Description of the versioned template of the Catalog Entry
  uuid: # Unique identifier to be used for upgrades. Please see note.
  minimum_rancher_version: v1.1.4 # The minimum version of Rancher that supports the template
  questions: 
    - variable: "k8s_address"
      label: "Address to connect to K8s service discovery (E.g. 40.12.1.65)"
      required: true
      type: "string"
    - variable: "k8s_api_secret"
      label: "K8s/Rancher API Key username"
      required: true
      type: "string"
    - variable: "k8s_api_password"
      label: "K8s/Rancher API Key password"
      required: true
      type: "string"
