name: EPPE # Name of the Catalog Entry
description: |
  Kubernetes catalog entry for a sample EPPE deployment# Description of the Catalog Entry
version: # Version of the Catalog to be used
category: demo # Category to be used for searching catalog entries
maintainer: Brandon Adams # The maintainer of the catalog entry
license: # The license
projectURL: newwave.io # A URL related to the catalog entry
