apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web-controller
  name: web-controller
  namespace: web
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: nwtspaderegistry-on.azurecr.io/nwtspade/mean:0.1.0
        name: web
        ports:
        - containerPort: 3000
          name: http-server
      nodeSelector:
        zone: web
      restartPolicy: Always
