apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
  labels:
    name: web-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
      protocol: TCP
  selector:
    name: web-controller