name: Mediscan
description: |
  Demo deployment of the Mediscan stack
version: 1.0
category: demo # Category to be used for searching catalog entries
maintainer: Brandon Adams # The maintainer of the catalog entry
license: # The license
projectURL: newwave.io # A URL related to the catalog entry
